version: '3'
services:
    mssql:
      image: mcr.microsoft.com/mssql/server:2022-latest
      container_name: mssqlserver01
      ports:
        - 1433:1433
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=s@Pass123
        - MSSQL_PID=Express
        - MSSQL_LCID=1041
        - MSSQL_COLLATION=Japanese_CI_AS
      volumes:
        - "./docker/mssqlserver/data:/var/opt/mssql/data"
        - "./docker/mssqlserver/log:/var/opt/mssql/log"
        - "./docker/mssqlserver/secrets:/var/opt/mssql/secrets"
